Hw02-express
khomasl/goit-node-hw-rest-api pull request #1
Opened 2021-12-20 21:00 UTC by khomasl

Пожалуйста проверьте.

2021-12-20 21:14 UTC, KirillKulakow commented on model/index.js
> +const listContacts = async () => contacts
почему асинхронная функция?

2021-12-20 21:14 UTC, KirillKulakow commented on model/index.js
> +const getContactById = async (contactId) =>
почему асинхронная?

2021-12-20 21:15 UTC, KirillKulakow commented on model/index.js
> +  const updatedContact = { id: contactId, ...contacts[id], ...body }
зачем перезаписывать ид?

2021-12-20 21:17 UTC, KirillKulakow requested changes
need refactor

2021-12-22 16:51 UTC, khomasl commented on model/index.js
> +const listContacts = async () => contacts
Спасибо.
Исправил

2021-12-22 16:51 UTC, khomasl commented on model/index.js
> +  const updatedContact = { id: contactId, ...contacts[id], ...body }
Спасибо.
Исправил

2021-12-22 19:20 UTC, KirillKulakow approved these changes

2021-12-22 19:38 UTC, merged