hw-03
khomasl/goit-node-hw-rest-api pull request #2
Opened 2021-12-28 21:21 UTC by khomasl

Пожалуйста проверьте.

2022-01-04 22:45 UTC, KirillKulakow commented on .env
> +URI_DB=mongodb+srv://user-35:1234@cluster0.xtfmg.mongodb.net/db-contacts
файл удалить из гитхаба и добавить в gitignore
эти данные не должны быть в гите

2022-01-04 22:48 UTC, KirillKulakow commented on repository/contacts.js
> +import Contact from '../model/contact'
не имею ничего против, можешь не исправлять
Но смысл в этом файле какой? ради функций однострочных?

2022-01-04 22:49 UTC, KirillKulakow requested changes
Need fix

2022-01-05 06:35 UTC, khomasl commented on repository/contacts.js
> +import Contact from '../model/contact'
Пока оставлю.

2022-01-05 06:35 UTC, khomasl commented on .env
> +URI_DB=mongodb+srv://user-35:1234@cluster0.xtfmg.mongodb.net/db-contacts
Спасибо.
Исправил.

2022-01-05 19:26 UTC, KirillKulakow approved these changes

2022-01-05 19:28 UTC, merged