hw-04
khomasl/goit-node-hw-rest-api pull request #3
Opened 2022-01-10 20:29 UTC by khomasl

Пожалуйста проверьте

2022-01-10 21:34 UTC, KirillKulakow commented on controllers/users/index.js
> +  const user = await req.user
почему await?

2022-01-10 21:35 UTC, KirillKulakow requested changes
Need fix

2022-01-11 15:22 UTC, khomasl commented on controllers/users/index.js
> +  const user = await req.user
Точно, не надо - она же будет вызываться уже после guard.
Спасибо.

2022-01-11 20:15 UTC, KirillKulakow approved these changes

2022-01-12 09:12 UTC, merged