hw06
khomasl/goit-node-hw-rest-api pull request #5
Opened 2022-01-24 18:11 UTC by khomasl

Проверьте пожалуйста

2022-01-24 18:55 UTC, KirillKulakow commented on model/user.js
> +      default: randomUUID(),
при запуске приложения у всех юзеров будет один и тот же токен

2022-01-24 18:55 UTC, KirillKulakow requested changes
Need fix

2022-01-24 19:05 UTC, khomasl commented on model/user.js
> +      default: randomUUID(),
Изменил

2022-01-25 07:29 UTC, khomasl commented on model/user.js
> +      default: randomUUID(),
/users/verify/6c1fa74a-8ad5-4a6d-855a-4e860c76cd41
/users/verify/aa9c924f-1d2d-45ac-90a8-2c6e473187ff

При default: randomUUID() - тоже разные токены у 2-х разных пользователей.

2022-01-25 20:49 UTC, KirillKulakow commented on model/user.js
> +      default: uuidv4(),
сделай два запроса подряд на регистрацию без перезагрузки самого приложения и поймешь свою ошибку
исправить!

2022-01-25 20:49 UTC, KirillKulakow requested changes
Need fix

2022-01-25 21:07 UTC, khomasl commented on model/user.js
> +      default: uuidv4(),
Спасибо.
Вроде исправил

2022-01-26 18:14 UTC, KirillKulakow approved these changes

2022-01-26 19:45 UTC, merged